// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: grael.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RetryPolicy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaxAttempts   int32                  `protobuf:"varint,1,opt,name=max_attempts,json=maxAttempts,proto3" json:"max_attempts,omitempty"`
	Backoff       *durationpb.Duration   `protobuf:"bytes,2,opt,name=backoff,proto3" json:"backoff,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryPolicy) Reset() {
	*x = RetryPolicy{}
	mi := &file_grael_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryPolicy) ProtoMessage() {}

func (x *RetryPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_grael_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryPolicy.ProtoReflect.Descriptor instead.
func (*RetryPolicy) Descriptor() ([]byte, []int) {
	return file_grael_proto_rawDescGZIP(), []int{0}
}

func (x *RetryPolicy) GetMaxAttempts() int32 {
	if x != nil {
		return x.MaxAttempts
	}
	return 0
}

func (x *RetryPolicy) GetBackoff() *durationpb.Duration {
	if x != nil {
		return x.Backoff
	}
	return nil
}

type NodeDefinition struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ActivityType         string                 `protobuf:"bytes,2,opt,name=activity_type,json=activityType,proto3" json:"activity_type,omitempty"`
	Input                *structpb.Struct       `protobuf:"bytes,9,opt,name=input,proto3" json:"input,omitempty"`
	DependsOn            []string               `protobuf:"bytes,3,rep,name=depends_on,json=dependsOn,proto3" json:"depends_on,omitempty"`
	RetryPolicy          *RetryPolicy           `protobuf:"bytes,4,opt,name=retry_policy,json=retryPolicy,proto3" json:"retry_policy,omitempty"`
	CompensationActivity string                 `protobuf:"bytes,5,opt,name=compensation_activity,json=compensationActivity,proto3" json:"compensation_activity,omitempty"`
	CheckpointTimeout    *durationpb.Duration   `protobuf:"bytes,6,opt,name=checkpoint_timeout,json=checkpointTimeout,proto3" json:"checkpoint_timeout,omitempty"`
	ExecutionDeadline    *durationpb.Duration   `protobuf:"bytes,7,opt,name=execution_deadline,json=executionDeadline,proto3" json:"execution_deadline,omitempty"`
	AbsoluteDeadline     *durationpb.Duration   `protobuf:"bytes,8,opt,name=absolute_deadline,json=absoluteDeadline,proto3" json:"absolute_deadline,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *NodeDefinition) Reset() {
	*x = NodeDefinition{}
	mi := &file_grael_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeDefinition) ProtoMessage() {}

func (x *NodeDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_grael_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeDefinition.ProtoReflect.Descriptor instead.
func (*NodeDefinition) Descriptor() ([]byte, []int) {
	return file_grael_proto_rawDescGZIP(), []int{1}
}

func (x *NodeDefinition) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NodeDefinition) GetActivityType() string {
	if x != nil {
		return x.ActivityType
	}
	return ""
}

func (x *NodeDefinition) GetInput() *structpb.Struct {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *NodeDefinition) GetDependsOn() []string {
	if x != nil {
		return x.DependsOn
	}
	return nil
}

func (x *NodeDefinition) GetRetryPolicy() *RetryPolicy {
	if x != nil {
		return x.RetryPolicy
	}
	return nil
}

func (x *NodeDefinition) GetCompensationActivity() string {
	if x != nil {
		return x.CompensationActivity
	}
	return ""
}

func (x *NodeDefinition) GetCheckpointTimeout() *durationpb.Duration {
	if x != nil {
		return x.CheckpointTimeout
	}
	return nil
}

func (x *NodeDefinition) GetExecutionDeadline() *durationpb.Duration {
	if x != nil {
		return x.ExecutionDeadline
	}
	return nil
}

func (x *NodeDefinition) GetAbsoluteDeadline() *durationpb.Duration {
	if x != nil {
		return x.AbsoluteDeadline
	}
	return nil
}

type WorkflowDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Nodes         []*NodeDefinition      `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowDefinition) Reset() {
	*x = WorkflowDefinition{}
	mi := &file_grael_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowDefinition) ProtoMessage() {}

func (x *WorkflowDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_grael_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowDefinition.ProtoReflect.Descriptor instead.
func (*WorkflowDefinition) Descriptor() ([]byte, []int) {
	return file_grael_proto_rawDescGZIP(), []int{2}
}

func (x *WorkflowDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WorkflowDefinition) GetNodes() []*NodeDefinition {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type StartRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workflow      *WorkflowDefinition    `protobuf:"bytes,1,opt,name=workflow,proto3" json:"workflow,omitempty"`
	Input         *structpb.Struct       `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRunRequest) Reset() {
	*x = StartRunRequest{}
	mi := &file_grael_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRunRequest) ProtoMessage() {}

func (x *StartRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grael_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRunRequest.ProtoReflect.Descriptor instead.
func (*StartRunRequest) Descriptor() ([]byte, []int) {
	return file_grael_proto_rawDescGZIP(), []int{3}
}

func (x *StartRunRequest) GetWorkflow() *WorkflowDefinition {
	if x != nil {
		return x.Workflow
	}
	return nil
}

func (x *StartRunRequest) GetInput() *structpb.Struct {
	if x != nil {
		return x.Input
	}
	return nil
}

type StartRunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRunResponse) Reset() {
	*x = StartRunResponse{}
	mi := &file_grael_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRunResponse) ProtoMessage() {}

func (x *StartRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grael_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRunResponse.ProtoReflect.Descriptor instead.
func (*StartRunResponse) Descriptor() ([]byte, []int) {
	return file_grael_proto_rawDescGZIP(), []int{4}
}

func (x *StartRunResponse) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type CancelRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRunRequest) Reset() {
	*x = CancelRunRequest{}
	mi := &file_grael_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRunRequest) ProtoMessage() {}

func (x *CancelRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grael_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRunRequest.ProtoReflect.Descriptor instead.
func (*CancelRunRequest) Descriptor() ([]byte, []int) {
	return file_grael_proto_rawDescGZIP(), []int{5}
}

func (x *CancelRunRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type ApproveCheckpointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveCheckpointRequest) Reset() {
	*x = ApproveCheckpointRequest{}
	mi := &file_grael_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveCheckpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveCheckpointRequest) ProtoMessage() {}

func (x *ApproveCheckpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grael_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveCheckpointRequest.ProtoReflect.Descriptor instead.
func (*ApproveCheckpointRequest) Descriptor() ([]byte, []int) {
	return file_grael_proto_rawDescGZIP(), []int{6}
}

func (x *ApproveCheckpointRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ApproveCheckpointRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type GetRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRunRequest) Reset() {
	*x = GetRunRequest{}
	mi := &file_grael_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRunRequest) ProtoMessage() {}

func (x *GetRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grael_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRunRequest.ProtoReflect.Descriptor instead.
func (*GetRunRequest) Descriptor() ([]byte, []int) {
	return file_grael_proto_rawDescGZIP(), []int{7}
}

func (x *GetRunRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type NodeView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ActivityType  string                 `protobuf:"bytes,2,opt,name=activity_type,json=activityType,proto3" json:"activity_type,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	DependsOn     []string               `protobuf:"bytes,4,rep,name=depends_on,json=dependsOn,proto3" json:"depends_on,omitempty"`
	Attempt       uint32                 `protobuf:"varint,5,opt,name=attempt,proto3" json:"attempt,omitempty"`
	WorkerId      string                 `protobuf:"bytes,6,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	LastError     string                 `protobuf:"bytes,7,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeView) Reset() {
	*x = NodeView{}
	mi := &file_grael_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeView) ProtoMessage() {}

func (x *NodeView) ProtoReflect() protoreflect.Message {
	mi := &file_grael_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeView.ProtoReflect.Descriptor instead.
func (*NodeView) Descriptor() ([]byte, []int) {
	return file_grael_proto_rawDescGZIP(), []int{8}
}

func (x *NodeView) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NodeView) GetActivityType() string {
	if x != nil {
		return x.ActivityType
	}
	return ""
}

func (x *NodeView) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *NodeView) GetDependsOn() []string {
	if x != nil {
		return x.DependsOn
	}
	return nil
}

func (x *NodeView) GetAttempt() uint32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *NodeView) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *NodeView) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

type RunView struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RunId          string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Workflow       string                 `protobuf:"bytes,2,opt,name=workflow,proto3" json:"workflow,omitempty"`
	DefinitionHash string                 `protobuf:"bytes,3,opt,name=definition_hash,json=definitionHash,proto3" json:"definition_hash,omitempty"`
	State          string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	LastSeq        uint64                 `protobuf:"varint,5,opt,name=last_seq,json=lastSeq,proto3" json:"last_seq,omitempty"`
	Nodes          map[string]*NodeView   `protobuf:"bytes,6,rep,name=nodes,proto3" json:"nodes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	FinishedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RunView) Reset() {
	*x = RunView{}
	mi := &file_grael_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunView) ProtoMessage() {}

func (x *RunView) ProtoReflect() protoreflect.Message {
	mi := &file_grael_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunView.ProtoReflect.Descriptor instead.
func (*RunView) Descriptor() ([]byte, []int) {
	return file_grael_proto_rawDescGZIP(), []int{9}
}

func (x *RunView) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *RunView) GetWorkflow() string {
	if x != nil {
		return x.Workflow
	}
	return ""
}

func (x *RunView) GetDefinitionHash() string {
	if x != nil {
		return x.DefinitionHash
	}
	return ""
}

func (x *RunView) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *RunView) GetLastSeq() uint64 {
	if x != nil {
		return x.LastSeq
	}
	return 0
}

func (x *RunView) GetNodes() map[string]*NodeView {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *RunView) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *RunView) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

type StreamEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	FromSeq       uint64                 `protobuf:"varint,2,opt,name=from_seq,json=fromSeq,proto3" json:"from_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEventsRequest) Reset() {
	*x = StreamEventsRequest{}
	mi := &file_grael_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEventsRequest) ProtoMessage() {}

func (x *StreamEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grael_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEventsRequest.ProtoReflect.Descriptor instead.
func (*StreamEventsRequest) Descriptor() ([]byte, []int) {
	return file_grael_proto_rawDescGZIP(), []int{10}
}

func (x *StreamEventsRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *StreamEventsRequest) GetFromSeq() uint64 {
	if x != nil {
		return x.FromSeq
	}
	return 0
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	RunId         string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Payload       []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_grael_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_grael_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_grael_proto_rawDescGZIP(), []int{11}
}

func (x *Event) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Event) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *Event) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Event) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Event) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type RegisterWorkerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	ActivityTypes []string               `protobuf:"bytes,2,rep,name=activity_types,json=activityTypes,proto3" json:"activity_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterWorkerRequest) Reset() {
	*x = RegisterWorkerRequest{}
	mi := &file_grael_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWorkerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWorkerRequest) ProtoMessage() {}

func (x *RegisterWorkerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grael_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWorkerRequest.ProtoReflect.Descriptor instead.
func (*RegisterWorkerRequest) Descriptor() ([]byte, []int) {
	return file_grael_proto_rawDescGZIP(), []int{12}
}

func (x *RegisterWorkerRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *RegisterWorkerRequest) GetActivityTypes() []string {
	if x != nil {
		return x.ActivityTypes
	}
	return nil
}

type PollTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	TimeoutMs     int64                  `protobuf:"varint,2,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollTaskRequest) Reset() {
	*x = PollTaskRequest{}
	mi := &file_grael_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollTaskRequest) ProtoMessage() {}

func (x *PollTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grael_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollTaskRequest.ProtoReflect.Descriptor instead.
func (*PollTaskRequest) Descriptor() ([]byte, []int) {
	return file_grael_proto_rawDescGZIP(), []int{13}
}

func (x *PollTaskRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *PollTaskRequest) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type WorkerTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ActivityType  string                 `protobuf:"bytes,3,opt,name=activity_type,json=activityType,proto3" json:"activity_type,omitempty"`
	Attempt       uint32                 `protobuf:"varint,4,opt,name=attempt,proto3" json:"attempt,omitempty"`
	Compensation  bool                   `protobuf:"varint,5,opt,name=compensation,proto3" json:"compensation,omitempty"`
	Workflow      string                 `protobuf:"bytes,6,opt,name=workflow,proto3" json:"workflow,omitempty"`
	WorkflowInput *structpb.Struct       `protobuf:"bytes,7,opt,name=workflow_input,json=workflowInput,proto3" json:"workflow_input,omitempty"`
	NodeInput     *structpb.Struct       `protobuf:"bytes,8,opt,name=node_input,json=nodeInput,proto3" json:"node_input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerTask) Reset() {
	*x = WorkerTask{}
	mi := &file_grael_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerTask) ProtoMessage() {}

func (x *WorkerTask) ProtoReflect() protoreflect.Message {
	mi := &file_grael_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerTask.ProtoReflect.Descriptor instead.
func (*WorkerTask) Descriptor() ([]byte, []int) {
	return file_grael_proto_rawDescGZIP(), []int{14}
}

func (x *WorkerTask) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *WorkerTask) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *WorkerTask) GetActivityType() string {
	if x != nil {
		return x.ActivityType
	}
	return ""
}

func (x *WorkerTask) GetAttempt() uint32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *WorkerTask) GetCompensation() bool {
	if x != nil {
		return x.Compensation
	}
	return false
}

func (x *WorkerTask) GetWorkflow() string {
	if x != nil {
		return x.Workflow
	}
	return ""
}

func (x *WorkerTask) GetWorkflowInput() *structpb.Struct {
	if x != nil {
		return x.WorkflowInput
	}
	return nil
}

func (x *WorkerTask) GetNodeInput() *structpb.Struct {
	if x != nil {
		return x.NodeInput
	}
	return nil
}

type PollTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *WorkerTask            `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollTaskResponse) Reset() {
	*x = PollTaskResponse{}
	mi := &file_grael_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollTaskResponse) ProtoMessage() {}

func (x *PollTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grael_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollTaskResponse.ProtoReflect.Descriptor instead.
func (*PollTaskResponse) Descriptor() ([]byte, []int) {
	return file_grael_proto_rawDescGZIP(), []int{15}
}

func (x *PollTaskResponse) GetTask() *WorkerTask {
	if x != nil {
		return x.Task
	}
	return nil
}

type CheckpointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckpointRequest) Reset() {
	*x = CheckpointRequest{}
	mi := &file_grael_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckpointRequest) ProtoMessage() {}

func (x *CheckpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grael_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckpointRequest.ProtoReflect.Descriptor instead.
func (*CheckpointRequest) Descriptor() ([]byte, []int) {
	return file_grael_proto_rawDescGZIP(), []int{16}
}

func (x *CheckpointRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CompleteTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	RunId         string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Attempt       uint32                 `protobuf:"varint,4,opt,name=attempt,proto3" json:"attempt,omitempty"`
	Compensation  bool                   `protobuf:"varint,5,opt,name=compensation,proto3" json:"compensation,omitempty"`
	Output        *structpb.Struct       `protobuf:"bytes,6,opt,name=output,proto3" json:"output,omitempty"`
	Checkpoint    *CheckpointRequest     `protobuf:"bytes,7,opt,name=checkpoint,proto3" json:"checkpoint,omitempty"`
	SpawnedNodes  []*NodeDefinition      `protobuf:"bytes,8,rep,name=spawned_nodes,json=spawnedNodes,proto3" json:"spawned_nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteTaskRequest) Reset() {
	*x = CompleteTaskRequest{}
	mi := &file_grael_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteTaskRequest) ProtoMessage() {}

func (x *CompleteTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grael_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteTaskRequest.ProtoReflect.Descriptor instead.
func (*CompleteTaskRequest) Descriptor() ([]byte, []int) {
	return file_grael_proto_rawDescGZIP(), []int{17}
}

func (x *CompleteTaskRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *CompleteTaskRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *CompleteTaskRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *CompleteTaskRequest) GetAttempt() uint32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *CompleteTaskRequest) GetCompensation() bool {
	if x != nil {
		return x.Compensation
	}
	return false
}

func (x *CompleteTaskRequest) GetOutput() *structpb.Struct {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *CompleteTaskRequest) GetCheckpoint() *CheckpointRequest {
	if x != nil {
		return x.Checkpoint
	}
	return nil
}

func (x *CompleteTaskRequest) GetSpawnedNodes() []*NodeDefinition {
	if x != nil {
		return x.SpawnedNodes
	}
	return nil
}

type FailTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	RunId         string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Attempt       uint32                 `protobuf:"varint,4,opt,name=attempt,proto3" json:"attempt,omitempty"`
	Compensation  bool                   `protobuf:"varint,5,opt,name=compensation,proto3" json:"compensation,omitempty"`
	Message       string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	Cancelled     bool                   `protobuf:"varint,7,opt,name=cancelled,proto3" json:"cancelled,omitempty"`
	Retryable     bool                   `protobuf:"varint,8,opt,name=retryable,proto3" json:"retryable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FailTaskRequest) Reset() {
	*x = FailTaskRequest{}
	mi := &file_grael_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailTaskRequest) ProtoMessage() {}

func (x *FailTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grael_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailTaskRequest.ProtoReflect.Descriptor instead.
func (*FailTaskRequest) Descriptor() ([]byte, []int) {
	return file_grael_proto_rawDescGZIP(), []int{18}
}

func (x *FailTaskRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *FailTaskRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *FailTaskRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *FailTaskRequest) GetAttempt() uint32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *FailTaskRequest) GetCompensation() bool {
	if x != nil {
		return x.Compensation
	}
	return false
}

func (x *FailTaskRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *FailTaskRequest) GetCancelled() bool {
	if x != nil {
		return x.Cancelled
	}
	return false
}

func (x *FailTaskRequest) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	RunId         string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Attempt       uint32                 `protobuf:"varint,4,opt,name=attempt,proto3" json:"attempt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_grael_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grael_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_grael_proto_rawDescGZIP(), []int{19}
}

func (x *HeartbeatRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *HeartbeatRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *HeartbeatRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HeartbeatRequest) GetAttempt() uint32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

type ListEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsRequest) Reset() {
	*x = ListEventsRequest{}
	mi := &file_grael_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsRequest) ProtoMessage() {}

func (x *ListEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grael_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsRequest.ProtoReflect.Descriptor instead.
func (*ListEventsRequest) Descriptor() ([]byte, []int) {
	return file_grael_proto_rawDescGZIP(), []int{20}
}

func (x *ListEventsRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type ListEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsResponse) Reset() {
	*x = ListEventsResponse{}
	mi := &file_grael_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsResponse) ProtoMessage() {}

func (x *ListEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grael_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsResponse.ProtoReflect.Descriptor instead.
func (*ListEventsResponse) Descriptor() ([]byte, []int) {
	return file_grael_proto_rawDescGZIP(), []int{21}
}

func (x *ListEventsResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

var File_grael_proto protoreflect.FileDescriptor

const file_grael_proto_rawDesc = "" +
	"\n" +
	"\vgrael.proto\x12\bgrael.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"e\n" +
	"\vRetryPolicy\x12!\n" +
	"\fmax_attempts\x18\x01 \x01(\x05R\vmaxAttempts\x123\n" +
	"\abackoff\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\abackoff\"\xde\x03\n" +
	"\x0eNodeDefinition\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\ractivity_type\x18\x02 \x01(\tR\factivityType\x12-\n" +
	"\x05input\x18\t \x01(\v2\x17.google.protobuf.StructR\x05input\x12\x1d\n" +
	"\n" +
	"depends_on\x18\x03 \x03(\tR\tdependsOn\x128\n" +
	"\fretry_policy\x18\x04 \x01(\v2\x15.grael.v1.RetryPolicyR\vretryPolicy\x123\n" +
	"\x15compensation_activity\x18\x05 \x01(\tR\x14compensationActivity\x12H\n" +
	"\x12checkpoint_timeout\x18\x06 \x01(\v2\x19.google.protobuf.DurationR\x11checkpointTimeout\x12H\n" +
	"\x12execution_deadline\x18\a \x01(\v2\x19.google.protobuf.DurationR\x11executionDeadline\x12F\n" +
	"\x11absolute_deadline\x18\b \x01(\v2\x19.google.protobuf.DurationR\x10absoluteDeadline\"X\n" +
	"\x12WorkflowDefinition\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12.\n" +
	"\x05nodes\x18\x02 \x03(\v2\x18.grael.v1.NodeDefinitionR\x05nodes\"z\n" +
	"\x0fStartRunRequest\x128\n" +
	"\bworkflow\x18\x01 \x01(\v2\x1c.grael.v1.WorkflowDefinitionR\bworkflow\x12-\n" +
	"\x05input\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x05input\")\n" +
	"\x10StartRunResponse\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\")\n" +
	"\x10CancelRunRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\"J\n" +
	"\x18ApproveCheckpointRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\"&\n" +
	"\rGetRunRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\"\xca\x01\n" +
	"\bNodeView\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\ractivity_type\x18\x02 \x01(\tR\factivityType\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x1d\n" +
	"\n" +
	"depends_on\x18\x04 \x03(\tR\tdependsOn\x12\x18\n" +
	"\aattempt\x18\x05 \x01(\rR\aattempt\x12\x1b\n" +
	"\tworker_id\x18\x06 \x01(\tR\bworkerId\x12\x1d\n" +
	"\n" +
	"last_error\x18\a \x01(\tR\tlastError\"\x90\x03\n" +
	"\aRunView\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x1a\n" +
	"\bworkflow\x18\x02 \x01(\tR\bworkflow\x12'\n" +
	"\x0fdefinition_hash\x18\x03 \x01(\tR\x0edefinitionHash\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x12\x19\n" +
	"\blast_seq\x18\x05 \x01(\x04R\alastSeq\x122\n" +
	"\x05nodes\x18\x06 \x03(\v2\x1c.grael.v1.RunView.NodesEntryR\x05nodes\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12;\n" +
	"\vfinished_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt\x1aL\n" +
	"\n" +
	"NodesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.grael.v1.NodeViewR\x05value:\x028\x01\"G\n" +
	"\x13StreamEventsRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x19\n" +
	"\bfrom_seq\x18\x02 \x01(\x04R\afromSeq\"\x98\x01\n" +
	"\x05Event\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\"[\n" +
	"\x15RegisterWorkerRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12%\n" +
	"\x0eactivity_types\x18\x02 \x03(\tR\ractivityTypes\"M\n" +
	"\x0fPollTaskRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x02 \x01(\x03R\ttimeoutMs\"\xb3\x02\n" +
	"\n" +
	"WorkerTask\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12#\n" +
	"\ractivity_type\x18\x03 \x01(\tR\factivityType\x12\x18\n" +
	"\aattempt\x18\x04 \x01(\rR\aattempt\x12\"\n" +
	"\fcompensation\x18\x05 \x01(\bR\fcompensation\x12\x1a\n" +
	"\bworkflow\x18\x06 \x01(\tR\bworkflow\x12>\n" +
	"\x0eworkflow_input\x18\a \x01(\v2\x17.google.protobuf.StructR\rworkflowInput\x126\n" +
	"\n" +
	"node_input\x18\b \x01(\v2\x17.google.protobuf.StructR\tnodeInput\"<\n" +
	"\x10PollTaskResponse\x12(\n" +
	"\x04task\x18\x01 \x01(\v2\x14.grael.v1.WorkerTaskR\x04task\"+\n" +
	"\x11CheckpointRequest\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"\xcd\x02\n" +
	"\x13CompleteTaskRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aattempt\x18\x04 \x01(\rR\aattempt\x12\"\n" +
	"\fcompensation\x18\x05 \x01(\bR\fcompensation\x12/\n" +
	"\x06output\x18\x06 \x01(\v2\x17.google.protobuf.StructR\x06output\x12;\n" +
	"\n" +
	"checkpoint\x18\a \x01(\v2\x1b.grael.v1.CheckpointRequestR\n" +
	"checkpoint\x12=\n" +
	"\rspawned_nodes\x18\b \x03(\v2\x18.grael.v1.NodeDefinitionR\fspawnedNodes\"\xf2\x01\n" +
	"\x0fFailTaskRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aattempt\x18\x04 \x01(\rR\aattempt\x12\"\n" +
	"\fcompensation\x18\x05 \x01(\bR\fcompensation\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\x12\x1c\n" +
	"\tcancelled\x18\a \x01(\bR\tcancelled\x12\x1c\n" +
	"\tretryable\x18\b \x01(\bR\tretryable\"y\n" +
	"\x10HeartbeatRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aattempt\x18\x04 \x01(\rR\aattempt\"*\n" +
	"\x11ListEventsRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\"=\n" +
	"\x12ListEventsResponse\x12'\n" +
	"\x06events\x18\x01 \x03(\v2\x0f.grael.v1.EventR\x06events2\xf2\x05\n" +
	"\x05Grael\x12A\n" +
	"\bStartRun\x12\x19.grael.v1.StartRunRequest\x1a\x1a.grael.v1.StartRunResponse\x12?\n" +
	"\tCancelRun\x12\x1a.grael.v1.CancelRunRequest\x1a\x16.google.protobuf.Empty\x12O\n" +
	"\x11ApproveCheckpoint\x12\".grael.v1.ApproveCheckpointRequest\x1a\x16.google.protobuf.Empty\x124\n" +
	"\x06GetRun\x12\x17.grael.v1.GetRunRequest\x1a\x11.grael.v1.RunView\x12@\n" +
	"\fStreamEvents\x12\x1d.grael.v1.StreamEventsRequest\x1a\x0f.grael.v1.Event0\x01\x12I\n" +
	"\x0eRegisterWorker\x12\x1f.grael.v1.RegisterWorkerRequest\x1a\x16.google.protobuf.Empty\x12A\n" +
	"\bPollTask\x12\x19.grael.v1.PollTaskRequest\x1a\x1a.grael.v1.PollTaskResponse\x12E\n" +
	"\fCompleteTask\x12\x1d.grael.v1.CompleteTaskRequest\x1a\x16.google.protobuf.Empty\x12=\n" +
	"\bFailTask\x12\x19.grael.v1.FailTaskRequest\x1a\x16.google.protobuf.Empty\x12?\n" +
	"\tHeartbeat\x12\x1a.grael.v1.HeartbeatRequest\x1a\x16.google.protobuf.Empty\x12G\n" +
	"\n" +
	"ListEvents\x12\x1b.grael.v1.ListEventsRequest\x1a\x1c.grael.v1.ListEventsResponseB!Z\x1fgrael/internal/grpcserver/pb;pbb\x06proto3"

var (
	file_grael_proto_rawDescOnce sync.Once
	file_grael_proto_rawDescData []byte
)

func file_grael_proto_rawDescGZIP() []byte {
	file_grael_proto_rawDescOnce.Do(func() {
		file_grael_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grael_proto_rawDesc), len(file_grael_proto_rawDesc)))
	})
	return file_grael_proto_rawDescData
}

var file_grael_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_grael_proto_goTypes = []any{
	(*RetryPolicy)(nil),              // 0: grael.v1.RetryPolicy
	(*NodeDefinition)(nil),           // 1: grael.v1.NodeDefinition
	(*WorkflowDefinition)(nil),       // 2: grael.v1.WorkflowDefinition
	(*StartRunRequest)(nil),          // 3: grael.v1.StartRunRequest
	(*StartRunResponse)(nil),         // 4: grael.v1.StartRunResponse
	(*CancelRunRequest)(nil),         // 5: grael.v1.CancelRunRequest
	(*ApproveCheckpointRequest)(nil), // 6: grael.v1.ApproveCheckpointRequest
	(*GetRunRequest)(nil),            // 7: grael.v1.GetRunRequest
	(*NodeView)(nil),                 // 8: grael.v1.NodeView
	(*RunView)(nil),                  // 9: grael.v1.RunView
	(*StreamEventsRequest)(nil),      // 10: grael.v1.StreamEventsRequest
	(*Event)(nil),                    // 11: grael.v1.Event
	(*RegisterWorkerRequest)(nil),    // 12: grael.v1.RegisterWorkerRequest
	(*PollTaskRequest)(nil),          // 13: grael.v1.PollTaskRequest
	(*WorkerTask)(nil),               // 14: grael.v1.WorkerTask
	(*PollTaskResponse)(nil),         // 15: grael.v1.PollTaskResponse
	(*CheckpointRequest)(nil),        // 16: grael.v1.CheckpointRequest
	(*CompleteTaskRequest)(nil),      // 17: grael.v1.CompleteTaskRequest
	(*FailTaskRequest)(nil),          // 18: grael.v1.FailTaskRequest
	(*HeartbeatRequest)(nil),         // 19: grael.v1.HeartbeatRequest
	(*ListEventsRequest)(nil),        // 20: grael.v1.ListEventsRequest
	(*ListEventsResponse)(nil),       // 21: grael.v1.ListEventsResponse
	nil,                              // 22: grael.v1.RunView.NodesEntry
	(*durationpb.Duration)(nil),      // 23: google.protobuf.Duration
	(*structpb.Struct)(nil),          // 24: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),    // 25: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),            // 26: google.protobuf.Empty
}
var file_grael_proto_depIdxs = []int32{
	23, // 0: grael.v1.RetryPolicy.backoff:type_name -> google.protobuf.Duration
	24, // 1: grael.v1.NodeDefinition.input:type_name -> google.protobuf.Struct
	0,  // 2: grael.v1.NodeDefinition.retry_policy:type_name -> grael.v1.RetryPolicy
	23, // 3: grael.v1.NodeDefinition.checkpoint_timeout:type_name -> google.protobuf.Duration
	23, // 4: grael.v1.NodeDefinition.execution_deadline:type_name -> google.protobuf.Duration
	23, // 5: grael.v1.NodeDefinition.absolute_deadline:type_name -> google.protobuf.Duration
	1,  // 6: grael.v1.WorkflowDefinition.nodes:type_name -> grael.v1.NodeDefinition
	2,  // 7: grael.v1.StartRunRequest.workflow:type_name -> grael.v1.WorkflowDefinition
	24, // 8: grael.v1.StartRunRequest.input:type_name -> google.protobuf.Struct
	22, // 9: grael.v1.RunView.nodes:type_name -> grael.v1.RunView.NodesEntry
	25, // 10: grael.v1.RunView.created_at:type_name -> google.protobuf.Timestamp
	25, // 11: grael.v1.RunView.finished_at:type_name -> google.protobuf.Timestamp
	25, // 12: grael.v1.Event.timestamp:type_name -> google.protobuf.Timestamp
	24, // 13: grael.v1.WorkerTask.workflow_input:type_name -> google.protobuf.Struct
	24, // 14: grael.v1.WorkerTask.node_input:type_name -> google.protobuf.Struct
	14, // 15: grael.v1.PollTaskResponse.task:type_name -> grael.v1.WorkerTask
	24, // 16: grael.v1.CompleteTaskRequest.output:type_name -> google.protobuf.Struct
	16, // 17: grael.v1.CompleteTaskRequest.checkpoint:type_name -> grael.v1.CheckpointRequest
	1,  // 18: grael.v1.CompleteTaskRequest.spawned_nodes:type_name -> grael.v1.NodeDefinition
	11, // 19: grael.v1.ListEventsResponse.events:type_name -> grael.v1.Event
	8,  // 20: grael.v1.RunView.NodesEntry.value:type_name -> grael.v1.NodeView
	3,  // 21: grael.v1.Grael.StartRun:input_type -> grael.v1.StartRunRequest
	5,  // 22: grael.v1.Grael.CancelRun:input_type -> grael.v1.CancelRunRequest
	6,  // 23: grael.v1.Grael.ApproveCheckpoint:input_type -> grael.v1.ApproveCheckpointRequest
	7,  // 24: grael.v1.Grael.GetRun:input_type -> grael.v1.GetRunRequest
	10, // 25: grael.v1.Grael.StreamEvents:input_type -> grael.v1.StreamEventsRequest
	12, // 26: grael.v1.Grael.RegisterWorker:input_type -> grael.v1.RegisterWorkerRequest
	13, // 27: grael.v1.Grael.PollTask:input_type -> grael.v1.PollTaskRequest
	17, // 28: grael.v1.Grael.CompleteTask:input_type -> grael.v1.CompleteTaskRequest
	18, // 29: grael.v1.Grael.FailTask:input_type -> grael.v1.FailTaskRequest
	19, // 30: grael.v1.Grael.Heartbeat:input_type -> grael.v1.HeartbeatRequest
	20, // 31: grael.v1.Grael.ListEvents:input_type -> grael.v1.ListEventsRequest
	4,  // 32: grael.v1.Grael.StartRun:output_type -> grael.v1.StartRunResponse
	26, // 33: grael.v1.Grael.CancelRun:output_type -> google.protobuf.Empty
	26, // 34: grael.v1.Grael.ApproveCheckpoint:output_type -> google.protobuf.Empty
	9,  // 35: grael.v1.Grael.GetRun:output_type -> grael.v1.RunView
	11, // 36: grael.v1.Grael.StreamEvents:output_type -> grael.v1.Event
	26, // 37: grael.v1.Grael.RegisterWorker:output_type -> google.protobuf.Empty
	15, // 38: grael.v1.Grael.PollTask:output_type -> grael.v1.PollTaskResponse
	26, // 39: grael.v1.Grael.CompleteTask:output_type -> google.protobuf.Empty
	26, // 40: grael.v1.Grael.FailTask:output_type -> google.protobuf.Empty
	26, // 41: grael.v1.Grael.Heartbeat:output_type -> google.protobuf.Empty
	21, // 42: grael.v1.Grael.ListEvents:output_type -> grael.v1.ListEventsResponse
	32, // [32:43] is the sub-list for method output_type
	21, // [21:32] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_grael_proto_init() }
func file_grael_proto_init() {
	if File_grael_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grael_proto_rawDesc), len(file_grael_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grael_proto_goTypes,
		DependencyIndexes: file_grael_proto_depIdxs,
		MessageInfos:      file_grael_proto_msgTypes,
	}.Build()
	File_grael_proto = out.File
	file_grael_proto_goTypes = nil
	file_grael_proto_depIdxs = nil
}
